### ISSUE TITLE
website looks really simple make it better

### ISSUE THREAD

**Issue by iron-coder12** [Code2Charvi/portfolio#1]

**Comment by Code2Charvi** [comment]
Hello Shaurya Rathi,
I am a beginner in coding.
I make simple websites.
So I need to improve my websites more as you said.

Thank You,
Charvi
I

**Comment by iron-coder12** [comment]
oh ok I see do you need help?

**Comment by iron-coder12** [comment]
I can make a professional websites using php js and react html css

**Comment by iron-coder12** [comment]
ok

**Comment by iron-coder12** [comment]
ok
